//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblaccount
    {
    
            public int id { get; set; }

            [Display(Name = "User Name")]
            [Required(ErrorMessage = "This field is required")]
            [UIHint("username")]
            public string username { get; set; }

            [Required]
            [Display(Name = "Last Name")]
            public string LastName { get; set; }

            [Required]
            [Display(Name = "First Name")]
            public string FirstName { get; set; }

            [Display(Name = "Middle Name")]
            public string MiddleName { get; set; }

            [Required(ErrorMessage ="This field is required")]
            //[StringLength(30, MinimumLength = 8, ErrorMessage = "Password should be atleast 8 characters")]
            [RegularExpression("^[a-zA-Z0-9]*$", ErrorMessage = "Only Alphabets and Numbers allowed.")]
            [Display(Name = "Password")]
            [DataType(DataType.Password)]
            public string password { get; set; }

            [Required]
            [Display(Name = "Department")]
            public string department { get; set; }

            [Required]
            [Display(Name = "Branch")]
            public string branch { get; set; }

            [Required]
            [Display(Name = "Usertype")]
            public string usertype { get; set; }

            [Display(Name = "Status")]
            public string status { get; set; }
        
        public string LoginErrorMessage { get; set; }
    
        public List<tblaccount> AssignedTo { get; set; }
    }
}
