//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;

    public partial class tblequipment
    {
        
        public int equipmentsId { get; set; }
        [Required]
        public string AssetNumber { get; set; }
        [Required]
        public string SerialNumber { get; set; }
        [Required]
        public string Type { get; set; }
        [Required]
        public string Manufacturer { get; set; }

        [Required]
        [MaxLength(4, ErrorMessage = "Year should be at least 4 characters.")]
        [RegularExpression("^[0-9]+$", ErrorMessage = "Password should be numbers only.")]
        public string YearModel { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
        [Required]
        public string Branch { get; set; }
        [Required]
        public string Department { get; set; }

        public string Status { get; set; }
    }
}
