//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblequipment
    {
        public int equipId { get; set; }
        public string AssetNumber { get; set; }
        public string SerialNumber { get; set; }
        public string Type { get; set; }
        public string Manufacturer { get; set; }
        public string YearModel { get; set; }
        public string Description { get; set; }
        public string Branch { get; set; }
        public string Department { get; set; }
        public string EquipmentStatus { get; set; }
    }
}
