//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblticket
    {
        public int TicketId { get; set; }
        public string TicketNumber { get; set; }
        public string Problem { get; set; }
        public string Details { get; set; }
        public string Status { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string CreatedBy { get; set; }
        public string AssignedTo { get; set; }
        public string ApprovedBy { get; set; }
    }
}
